config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create]
  devise_for :users
  resources :users
  resources :nodes, only: [:show, :index, :create] 

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :author, class_name: "User", foreign_key: "user_id"
	belongs_to :node

end

app/models/node.rb
class Node < ActiveRecord::Base
	has_many :lists
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader       
  has_many :lists






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find_by_username(session[:username]) if session[:username]
  end













end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all.order(created_at: :desc).page(params[:page]).per(15)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :content)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy, :node_list]


  def index
  	@nodes = Node.all
  end

  def show
  	@node = Node.find(params[:id])
  end

  def new
  	@node = Node.new
  end

  def edit
  end

  def create
    @list = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name, :summary)
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController








end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper

	def markdown(content)
	  @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
	  @markdown.render(content)
	end






end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="top-bar">
    <ul class="title-area">
        <li class="name">
        <h1><a href="/">学习清单</a></h1>
        </li>
        <li class="toggle-topbar menu-icon">

        <a href="#">菜单</a>
        </li>
    </ul>

<section class="top-bar-section">
  <%if user_signed_in? %>
      <ul class="right">
        <li class="divider"></li>
        <li><%= link_to '创建清单', new_list_path %></li>
        <li class="divider"></li>
        <li><%=link_to "我", edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>         
  
        
         
      </ul>
  <% else %>
      <ul class="right">
          <li class="divider"></li>
          <li><%= link_to '注册', new_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to '登陆', new_user_session_path %></li>
      </ul>
  <% end %>

      <ul>
          <li class="has-form">
            <div class="row collapse">
              <div class="large-8 small-9 columns">
                <input type="text" placeholder="知识">
              </div>
              <div class="large-4 small-3 columns">
                <a href="#" class="alert button expand">搜索</a>
              </div>
            </div>
          </li>
      </ul>
  
</section>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
    <!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
      <!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
        <head>
          <meta charset="utf-8" />

          <!-- Uncomment to make IE8 render like IE7 -->
          <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

          <!-- Set the viewport width to device width for mobile -->
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />

          <title><%= content_for?(:title) ? yield(:title) : "学习清单" %></title>

          <%= stylesheet_link_tag    "application" %>
          <%= javascript_include_tag "vendor/custom.modernizr" %>
          <%= javascript_include_tag "vendor/modernizr" %>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <%= csrf_meta_tags %>
        </head>

        <body>

          <%= render 'layouts/header' %>
          <div class="row">
            <% if notice %>
              <p class="alert-box success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert-box error"><%= alert %></p>
            <% end %>
            
            <div class="large-12 columns">
              <%= yield %>
            </div>
          </div>


          <%= javascript_include_tag "application" %>
        </body>
      </html>

app/views/lists/_form.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= simple_form_for @list do |f| %>
        <% if @list.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

              <ul>
              <% @list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
        <% end %>

        <div class="input-group">
          <%= f.input :title, label: '标题', placeholder: "填写清单标题" %>
          <%= f.input :title, label: '标签', placeholder: "节点标签 比如: Ruby " %>           
        </div>

        <div class="list-body">
            <div>
                <%= f.input :content, label: '内容  (兼容 Markdown 格式)', class: "textarea" %>
            </div>
        </div>
        <br>

        <div class="actions">
          <%= f.submit :保存, class: "button" %>
        </div>
    <% end %>
  </div>
  <div class="small-5 columns">
    <%= link_to "预览", "#", class: "button warning", "data-toggle": "modal", " data-target": "#previewModal", id: "preview"  %>

    <div class="tabs-panel list_preview" id="panel2">

    </div>    
  </div>
</div>

app/views/lists/_list_list.html.erb
<ul class="lists box">
	<% lists.each do |list| %>
		<li>
			<h2 class="list_title">
				<%= link_to list.title, list %>
			</h2>
			<p>
			  <%= truncate(list.content, length: 99) %>
			  <br>			
			  <%= link_to list.node.name, list.node, class: "node" if list.node.present? %>	
	        </p>
		</li>
	<% end %>
</ul>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<br>
<br>
<div class="row">
  <div class="medium-8 columns">
    <%= render 'list_list', lists: @lists %>
    <br>
    <%= paginate @lists %>
  </div>
  

  <div class="medium-4 columns">
    <%= link_to '创建清单', new_list_path, class: "disabled button" %>
    <br>

  </div>
  
</div>

app/views/lists/new.html.erb
<h1>创建清单</h1>

<%= render 'form' %>

<%= link_to '返回首页', lists_path %>

app/views/lists/show.html.erb
<br>
<h2><%= @list.title %></h2>
<p>

  <%= @list.title %>
</p>
<br>

<div>
  <%= raw markdown(@list.content) %>
</div>
<br>
<br>
<br>
<br>
<% if user_signed_in? %>
	<%= link_to '修改', edit_list_path(@list), class: "tiny success hollow button" %>
<% end %>
<%= link_to '返回首页', lists_path, class: "tiny alert hollow button" %>

app/views/nodes/show.html.erb
<br>
<br>
<div class="row node_topics">
    <div class="medium-8 columns node_info">
		<h2><%= @node.name %></h2>
		<span>共有<%= @node.lists.count %>个学习清单</span>
		<p><%= @node.summary %></p>
		<%= render '/lists/list_list', lists: @node.lists %> 
	</div>

	<div class="sidebar medium-4 columns">
		<div id="new_list" class="box">
			<%= link_to "创建新清单", nil, class: "btn disabled" %>
		</div>
		<div id="stats" class="box">
			<ul>
				<li>社区会员: 2 人</li>
				<li>清单数: 456 篇</li>
				<li>回帖数</li>
			</ul>
		</div>
	</div>
</div>

app/views/shared/_breadcrumb.html.erb
_breadcrumb.html.erb

app/views/shared/_side_node.html.erb
<div class="nodes_list">
	标签: <br> <br>
	<% nodes.each do |node| %>
      <button class="secondary hollow button tiny">
        <% if list.node %>
          <%= link_to node.name, node %>
        <% end %>
      </button>
    <% end %> 
</div>

app/views/users/index.html.erb
<h2>用户</h2>
<div class="large-8 columns">
    <% @users.each do |user| %>
      <div class="user">
        <p><%= link_to user.name, user %></p>
        <p><%= link_to user.avatar, user %></p>
        <p><%= link_to user.email, user %></p>

      </div>
    <% end %> 
</div>

app/views/users/show.html.erb
<h1>个人信息</h2>
<% img(src="#{gravatar_url('2243980491@qq.com')}") %>
<dl>
	<dt class="span1"> ID: </dt>
	<dd>
		<strong><%= @user.name %></strong>
	</dd>
	<dt class="span1">Since: </dt>
	<dd><%= @user.created_at %></dd>
</dl>

<section id="user_recent_lists" class="box">
	<section id="user_recent_lists_banner" class="box info-box"><span>最近发布的帖子</span></section>
	<section id="user_recent_lists_content" class="box">
		<ul>
			<% @user.lists.each do |list| %>
				<li>
					<%= link_to list.node.name, list.node, class: "node" %>
					<%= link_to list.title, list %>
					<span><%= published at #{time_ago_in_words(list.created_at)} ago %></span>
				</li>
		</ul>
	</section>
</section>